site_name: HK Racing Project
site_url: https://ramgath.github.io/hk_racing_project/
docs_dir: docs
theme:
  name: material
extra_css:
  - css/overrides.css
nav:
  - Home: index.md
  - Project Plan: master-plan.md
  - Decisions: decisions.md
  - Project Status: project-status.md
  - Phase 1: phase-01-collection.md
  - Phase 2: phase-02-cleansing.md
  - Phase 3: phase-03-eda.md
  - Phase 4: phase-04-features.md
  - Phase 5: phase-05-model.md
  - Phase 6: phase-06-evaluation.md
  - Phase 7: phase-07-deployment.md
  - Phase 8: phase-08-management.md
