# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug Report
description: Report a problem or unexpected behavior
title: "[Bug] "
labels:
  - Type: Bug
body:
  - type: markdown
    attributes:
      value: |
        <!-- Help us squash this bug by filling out the sections below. -->
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe exactly how to reproduce this bug
      placeholder: "1. Go to ‘…’\n2. Click ‘…’\n3. Observe error"
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Observed Behavior
      description: What actually happened
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python/mkdocs versions, etc.
      placeholder: "macOS 13.4, Python 3.11"
      required: false
