# .github/ISSUE_TEMPLATE/task.yml
name: Task
description: Create a new project task or feature
title: "[Task] "
labels:
  - Type: Task
body:
  - type: markdown
    attributes:
      value: |
        <!-- Provide a clear, concise description of the task you want to accomplish. -->
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of what needs to be done
      placeholder: "e.g. Implement API client stub"
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria (one per line, prefixed `- [ ]`)
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context / Background
      description: Any links, screenshots or other context
      placeholder: "e.g. HKJC API docs link"
      required: false
