name: CI

# Trigger on pushes to any branch and on pull requests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson('["3.9", "3.10", "3.11"]') }}

    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 2b. Validate Python version
      - name: Validate Python version
        run: |
          case ${{ matrix.python-version }} in
            "3.9"|"3.10"|"3.11") echo "Python version allowed" ;;
            *) echo "Invalid Python version: ${{ matrix.python-version }}" && exit 1 ;;
          esac

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # 4. Run pre-commit (formatting, nbstripout, etc.)
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      # 5. Run linting (flake8)
      - name: Run flake8
        run: |
          flake8 .

      # 6. Check for test files
      - name: Check for test files
        run: |
          if ! find tests -name 'test_*.py' | grep -q .; then
            echo "❌ No test files found in tests/"
            exit 1
          fi

      # 7. Run tests
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
