name: Deploy Docs

# Run this workflow on pushes to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Install MkDocs (if you’re using MkDocs—skip or swap for Jekyll if not)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      # 3. Build the site into /site
      - name: Build documentation
        run: mkdocs build --site-dir site

      # 4. Deploy to GitHub Pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
